@startuml
entity RemoveBookFromCatalogActivity
entity CatalogDao

RemoveBookFromCatalogActivity --> CatalogDao : removeBookFromCatalog
RemoveBookFromCatalogActivity --> CatalogDao : execute
return BookNotFoundException
return RemoveBookFromCatalogResponse

@enduml
